### ISSUE TITLE
Questions around explicit channel closing

### ISSUE THREAD

**Issue by vincentdephily** [tqtrungse/omango#2]
Hi,

While trying omango out as a crossbeam_channel replacement, I was surprised that the `Sender<MyType>` going out of scope doesn't `close()` the channel, and that explicitly closing the sender makes the corresponding `rx.recv()` immediately fail even if there are messages left in the channel. I could get them with `try_recv()`, but then would have to deal with the non-blocking API.

Am I missing something, or is omango not intended for the "send finite list of items from one thread to another" usecase ?

**Comment by tqtrungse** [comment]
Hi,
That is the library's design to reduce the complexity of getting the remaining messages. When `close` is called, all APIs (including TX and RX) are blocked which will return immediately with `Channel Closed` error, then you should use `try_recv` to get the remaining messages. If `try_recv` doesn't return any message, the channel is empty because it has not received any more messages since it was closed.

"send finite list of items from one thread to another"
You can do it. If you don't close TX, everything is ok. If you close TX before Rx is complete, you should use more `try_recv`. 
It's not very good in convenience, but it is simple and gets good performance.

In the near future, I will try to find another way that is both convenient and effective for this problem.

**Comment by vincentdephily** [comment]
Hum, ok.

Not closing the channel is not an option, as I need to signal the end of the message list somehow, to allow to receive loop to finish. I'm not sure what the usecase is for keeping the channel open when the rx or tx is/are dropped.

I seem to get the desired behavior by using `while let(msg) = rx.recv().or_else(|_| rx.try_recv())`, but this feel needlessly complicated/inefficient, and it makes me wonder whether I'm masking errors unrelated to closed channels.

I couldn't measure a perf advantage compared to crossbeam for my usecase. Together with the unconvenient API, I'll stick with crossbeam for now. Feel free to close this issue if you think the omango API is fine.

Thanks.

**Comment by tqtrungse** [comment]
"as I need to signal the end of the message list somehow, to allow to receive loop to finish"

If the channel is closed, RX will be woken up and return `Channel closed error | Disconnected` -> It is the signal. Then you can use one more loop to get the remaining messages by `try_recv`. Is something wrong with this approach for you?

**Comment by vincentdephily** [comment]
Yes, closing the channel is the signal I need, I was countering your claim that "If you don't close TX, everything is ok": it's not ok, because I need my computation to end ;)

Just to be clear, here's what I do with crossbeam and most other channel crates:

```rust
let (tx,rx) = channel();
thread::spawn(move || {
  for i in 0..10 {tx.send(i).unwrap()}
});
for msg in rx {
  println!("{msg}");
}
```

With omango it's a bit more cumbersome:

```rust
let (tx,rx) = channel();
thread::spawn(move || {
  for i in 0..10 {tx.send(i).unwrap()}
  tx.close();
});
// Could also use two loops, as you suggested
while let Some(msg) = rx.recv().or_else(|_| rx.try_recv()) {
  println!("{msg}");
}
```

I don't mind a less convenient API if it opens up new possibilities or speeds up the implementation, but I don't see it here (correct me if I'm wrong):
* `rx.recv()` could succeed if there are messages in the channel, regardless of whether the channel is closed or not.
* Once the above is fixed, there isn't any need to keep the channel open after its `rx` has been `drop()`ed.
* `rx` implementing `IntoIterator` is a nice convenience.
